apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: harvester-ingress
  namespace: rancher 
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - harvester.gomes.dev
    secretName: harvester-tls
  rules:
  - host: harvester.gomes.dev
    http:
      paths:
      - backend:
          service:
            name: harvester-service # Here you specify the name of the Service traffic must be routed to
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific